// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRlevwV7vZqtHoDS25VuyJvlisDN8i9Vc',
    appId: '1:609071245287:web:c7a6d25ea7918ecd03bf42',
    messagingSenderId: '609071245287',
    projectId: 'magmug-2a095',
    authDomain: 'magmug-2a095.firebaseapp.com',
    storageBucket: 'magmug-2a095.firebasestorage.app',
    measurementId: 'G-KWCT0XJQYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPsu2l9auGBqiugBJguLa_01KH2aXNSI',
    appId: '1:609071245287:android:da24010c4271b4b203bf42',
    messagingSenderId: '609071245287',
    projectId: 'magmug-2a095',
    storageBucket: 'magmug-2a095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnaZEiKozSWdRC_K2-fAFuVO6_eJoYTU',
    appId: '1:609071245287:ios:1e3ba8dabfa819cd03bf42',
    messagingSenderId: '609071245287',
    projectId: 'magmug-2a095',
    storageBucket: 'magmug-2a095.firebasestorage.app',
    iosBundleId: 'com.magmug.magmug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnaZEiKozSWdRC_K2-fAFuVO6_eJoYTU',
    appId: '1:609071245287:ios:1e3ba8dabfa819cd03bf42',
    messagingSenderId: '609071245287',
    projectId: 'magmug-2a095',
    storageBucket: 'magmug-2a095.firebasestorage.app',
    iosBundleId: 'com.magmug.magmug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRlevwV7vZqtHoDS25VuyJvlisDN8i9Vc',
    appId: '1:609071245287:web:c3de5202f95ad77703bf42',
    messagingSenderId: '609071245287',
    projectId: 'magmug-2a095',
    authDomain: 'magmug-2a095.firebaseapp.com',
    storageBucket: 'magmug-2a095.firebasestorage.app',
    measurementId: 'G-4W5FCSR7J0',
  );
}
